fatal: [User_Network]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.488097-133543766773469 `\" && echo ansible-tmp-1746520717.488097-133543766773469=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.488097-133543766773469 `\" ), exited with result 254, stdout output: %% Unrecognized command:  \"/bin/sh -c '( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.488097-133543766773469 `\" && echo ansible-tmp-1746520717.488097-133543766773469=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.488097-133543766773469 `\" ) && sleep 0'\"\n%% Invalid input detected.\r\n", "unreachable": true}
fatal: [Local_Switch]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5213165-163017456982520 `\" && echo ansible-tmp-1746520717.5213165-163017456982520=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5213165-163017456982520 `\" ), exited with result 254, stdout output: %% Unrecognized command:  \"/bin/sh -c '( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5213165-163017456982520 `\" && echo ansible-tmp-1746520717.5213165-163017456982520=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5213165-163017456982520 `\" ) && sleep 0'\"\n%% Invalid input detected.\r\n", "unreachable": true}
fatal: [IT_Network]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5329022-182605988359590 `\" && echo ansible-tmp-1746520717.5329022-182605988359590=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5329022-182605988359590 `\" ), exited with result 254, stdout output: %% Unrecognized command:  \"/bin/sh -c '( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5329022-182605988359590 `\" && echo ansible-tmp-1746520717.5329022-182605988359590=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5329022-182605988359590 `\" ) && sleep 0'\"\n%% Invalid input detected.\r\n", "unreachable": true}
fatal: [MGMT_Network]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5393498-253989678568978 `\" && echo ansible-tmp-1746520717.5393498-253989678568978=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5393498-253989678568978 `\" ), exited with result 254, stdout output: %% Unrecognized command:  \"/bin/sh -c '( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5393498-253989678568978 `\" && echo ansible-tmp-1746520717.5393498-253989678568978=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.5393498-253989678568978 `\" ) && sleep 0'\"\n%% Invalid input detected.\r\n", "unreachable": true}
fatal: [ACCT_Network]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.560404-117847755115389 `\" && echo ansible-tmp-1746520717.560404-117847755115389=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.560404-117847755115389 `\" ), exited with result 254, stdout output: %% Unrecognized command:  \"/bin/sh -c '( umask 77 && mkdir -p \"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.560404-117847755115389 `\" && echo ansible-tmp-1746520717.560404-117847755115389=\"` echo %% Invalid input detected./.ansible/tmp/ansible-tmp-1746520717.560404-117847755115389 `\" ) && sleep 0'\"\n%% Invalid input detected.\r\n", "unreachable": true}
fatal: [Test_Box-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: admin@10.10.1.56: Permission denied (publickey,password).", "unreachable": true}
fatal: [Test_Box-2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: admin@10.10.1.57: Permission denied (publickey,password).", "unreachable": true}
